feat: Implement bot detection categories
arcjet/arcjet-js pull request #1618
Opened 2024-09-12 20:33 UTC by blaine-arcjet

This is mostly just codegen and a little bit of type updates.

I'm planning to add a new example for categories, with the additional demonstration of filtering items from a category.

2024-09-13 17:19 UTC, blaine-arcjet commented
@davidmytton I've added an example for the bot categories. Please try it out! I also included usage and details about your filtering request in the example.

2024-09-13 23:15 UTC, blaine-arcjet commented
Note to self: add this to dependabot and CI

2024-09-15 16:47 UTC, davidmytton requested changes
I tested the nextjs-14-bot-categories example app, but I don't get the category in the headers or when the decision is logged:

```
< HTTP/1.1 429 Too Many Requests
< vary: RSC, Next-Router-State-Tree, Next-Router-Prefetch
< content-type: application/json
< x-arcjet-bot-allowed:
< x-arcjet-bot-denied: CURL
< Date: Sun, 15 Sep 2024 16:45:40 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< Transfer-Encoding: chunked
<
* Connection #0 to host localhost left intact
{"error":"You are a Bot!"}%
```

```
ArcjetDenyDecision {
  id: 'req_01j7v96s53fc7btc6naz433qce',
  results: [
    ArcjetRuleResult {
      ruleId: '',
      ttl: 60,
      state: 'RUN',
      conclusion: 'DENY',
      reason: [ArcjetBotReason]
    }
  ],
  ttl: 60,
  ip: ArcjetIpDetails {
    latitude: undefined,
    longitude: undefined,
    accuracyRadius: undefined,
    timezone: undefined,
    postalCode: undefined,
    city: undefined,
    region: undefined,
    country: undefined,
    countryName: undefined,
    continent: undefined,
    continentName: undefined,
    asn: undefined,
    asnName: undefined,
    asnDomain: undefined,
    asnType: undefined,
    asnCountry: undefined,
    service: undefined
  },
  conclusion: 'DENY',
  reason: ArcjetBotReason { type: 'BOT', allowed: [], denied: [ 'CURL' ] }
```

2024-09-15 16:47 UTC, davidmytton commented on examples/nextjs-14-bot-categories/app/api/arcjet/route.ts
> +      { status: 429, headers },
```suggestion
      { status: 403, headers },
```

2024-09-16 15:44 UTC, blaine-arcjet commented
@davidmytton did you test against the decide service running locally? Since the example is using an `allow` list, if you tested against the test or prod server, you'd get CURL denied (as categories aren't supported until it is deployed). I also ran into this when testing so the result looks familiar.

2024-09-16 15:50 UTC, davidmytton approved these changes
Yeh I was testing against prod. Just tested against the local branch and all looks good!

2024-09-16 17:57 UTC, merged