chore(nosecone): Add JSDoc comments to NoseconeOptions
arcjet/arcjet-js pull request #2380
Opened 2024-11-29 23:17 UTC by blaine-arcjet

This adds JSDoc comments to every configuration option in `NoseconeOptions`. I needed these descriptions, links, etc in the reference guide so it made sense to add them here and migrate over.

2024-11-30 09:53 UTC, davidmytton requested changes
The main question this leaves is: what are the defaults? I think we should document those in the docs, but probably also in the `README` because that's what shows up on NPM etc. Then link to the docs in these comments. What were you planning @blaine-arcjet ?

2024-11-30 09:53 UTC, davidmytton commented on nosecone/index.ts
> +   * large number of * attacks, such as cross-site scripting.
```suggestion
   * large number of attacks, such as cross-site scripting.
```

2024-11-30 09:53 UTC, davidmytton commented on nosecone/index.ts
> +   * large number of * attacks, such as cross-site scripting.
Not sure if this was intentional - looks like a comment artifact.

2024-11-30 09:53 UTC, davidmytton commented on nosecone/index.ts
> +   * Disable the `X-XSS-Protection` header, which could introduce a browser
This is deprecated and doesn't work consistently across browsers. Should we add some note about that?

2024-12-02 16:28 UTC, davidmytton commented on nosecone/index.ts
> +   * Disable the `X-XSS-Protection` header, which could introduce a browser
Yeah fine if it's disabled by default.

Would love to see if any browsers are still using this! Must be years old at this point:

<img width="688" alt="image" src="https://github.com/user-attachments/assets/ac2603c4-a039-4df9-a42f-8c472efa7d9a">

2024-12-02 16:35 UTC, blaine-arcjet commented on nosecone/index.ts
> +   * side-channel if enabled.
```suggestion
   * side-channel in legacy browsers if enabled.
```

2024-12-02 16:52 UTC, blaine-arcjet commented
> The main question this leaves is: what are the defaults? I think we should document those in the docs, but probably also in the README because that's what shows up on NPM etc. Then link to the docs in these comments. What were you planning @blaine-arcjet ?

I agree, showing the defaults is going to be an important piece of documenting this. Adding to the README and our docs site seems good; and then I can link from the JSDoc to keep them from growing too large.

2024-12-03 10:57 UTC, davidmytton approved these changes

2024-12-03 15:38 UTC, merged