feat: support allow and deny config of validateEmail rule
arcjet/arcjet-js pull request #2661
Opened 2024-12-20 15:53 UTC by e-moran

2025-01-02 22:55 UTC, blaine-arcjet commented on arcjet/index.ts
> +type EmailOptionsAllow = {
```suggestion
export type EmailOptionsAllow = {
```
Need to export this to make documentation easier

2025-01-02 22:55 UTC, blaine-arcjet commented on arcjet/index.ts
> +type EmailOptionsDeny = {
```suggestion
export type EmailOptionsDeny = {
```
Need to export this to make documentation easier

2025-01-02 22:56 UTC, blaine-arcjet commented on arcjet/index.ts
>    validateEmailOptions(options);
You didn't update this validator

2025-01-02 22:59 UTC, blaine-arcjet requested changes
Accidentally submitted the other comments as single comments.

2025-01-02 22:59 UTC, blaine-arcjet commented on arcjet/index.ts
> +      allow: [],
Is "allow none" the right default here? I ask because we have "inverted" types, such as `NO_GRAVATAR`

2025-01-03 14:31 UTC, e-moran commented on arcjet/index.ts
> +      allow: [],
I had set it to "allow none" here so it would align with bot detection/sensitive info. I don't think the inverted types change that because `allow: []` still means "block everything that we can detect" in all cases. However that default makes less sense with emails because of how restrictive it is.

Do you think we should prioritize alignment with other rules, or follow what people are more likely to want from an email validation rule (in which case we might also consider `block: ["INVALID"]` as the default).

2025-01-03 14:32 UTC, e-moran commented on arcjet/index.ts
> +type EmailOptionsAllow = {
Fixed this, is there any reason this isn't the case for `BotOptionsAllow` and `BotOptionsDeny`?

2025-01-03 15:54 UTC, blaine-arcjet commented on arcjet/index.ts
> +type EmailOptionsAllow = {
Those need to be exported (among others). I discovered this while working on the `<DisplayType />` component in our docs. Do you want to open an issue?

2025-01-03 15:55 UTC, blaine-arcjet commented on arcjet/index.ts
>      { key: "block", required: false, validate: validateEmailTypes },
Block needs to be removed, right?

2025-01-03 16:00 UTC, blaine-arcjet commented on arcjet/index.ts
> +      allow: [],
I believe the idea (from long ago) was that primitives (e.g. `detectBot`/`validateEmail`) would be configured and not make assumptions about defaults, while products (e.g. `protectSignup`) would be preconfigured for common use cases.

We've strayed quite far from that because we never added more products and we've defaulted primitives to be the most open. For example, the current `validateEmail` blocks nothing if you don't set `block`.

I think your change to "deny none" keeps us in line with the current behavior but I'm not sure it is fundamentally ideal. Perhaps we open an issue/discussion for feedback.

2025-01-09 21:26 UTC, blaine-arcjet commented on arcjet/index.ts
> +  }
Shouldn't there be `allow && deny` check too?

2025-01-09 21:27 UTC, blaine-arcjet commented on arcjet/index.ts
> +  }
nvm, I was looking at a single commit.

2025-01-09 21:31 UTC, blaine-arcjet requested changes
This looks great. It just needs additional tests to ensure our validation works when TypeScript is ignored or not used.

2025-01-09 21:31 UTC, blaine-arcjet commented on arcjet/test/arcjet.test.ts
Please add tests that use `// @ts-expect-error` and validates config errors when allow/deny/block specified together or not specified.

2025-01-13 23:07 UTC, blaine-arcjet approved these changes
🎉 :shipit: 📧

2025-01-14 11:40 UTC, merged